#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Zadify.Resource", IsApplication=true)]

namespace Zadify
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int CompetitionForm = 2131034114;
			
			// aapt resource value: 0x7f050021
			public const int CompetitionsButton = 2131034145;
			
			// aapt resource value: 0x7f050017
			public const int CompletedGoalsButton = 2131034135;
			
			// aapt resource value: 0x7f050001
			public const int CompletedGoalsList = 2131034113;
			
			// aapt resource value: 0x7f050011
			public const int ConfirmDeleteGoalButton = 2131034129;
			
			// aapt resource value: 0x7f050008
			public const int CreateCompetitionButton = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int CreateCustomGoalButton = 2131034119;
			
			// aapt resource value: 0x7f050015
			public const int CreateGoalButton = 2131034133;
			
			// aapt resource value: 0x7f050006
			public const int CreatePredefinedGoalButton = 2131034118;
			
			// aapt resource value: 0x7f05000f
			public const int CreateRewardButton = 2131034127;
			
			// aapt resource value: 0x7f050004
			public const int CustomGoalForm = 2131034116;
			
			// aapt resource value: 0x7f05000d
			public const int CustomRewardDetails = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int CustomRewardForm = 2131034123;
			
			// aapt resource value: 0x7f05001e
			public const int CustomRewardsButton = 2131034142;
			
			// aapt resource value: 0x7f050010
			public const int CustomRewardsList = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int DeleteCustomRewardButton = 2131034126;
			
			// aapt resource value: 0x7f050014
			public const int DeleteGoalButton = 2131034132;
			
			// aapt resource value: 0x7f050012
			public const int GoalDetails = 2131034130;
			
			// aapt resource value: 0x7f050018
			public const int GoalsButton = 2131034136;
			
			// aapt resource value: 0x7f050016
			public const int GoalsList = 2131034134;
			
			// aapt resource value: 0x7f050000
			public const int NewCompetitionButton = 2131034112;
			
			// aapt resource value: 0x7f050020
			public const int NewsFeedButton = 2131034144;
			
			// aapt resource value: 0x7f050009
			public const int PredefinedGoalForm = 2131034121;
			
			// aapt resource value: 0x7f050025
			public const int RanksButton = 2131034149;
			
			// aapt resource value: 0x7f05001c
			public const int RanksList = 2131034140;
			
			// aapt resource value: 0x7f050019
			public const int RewardsButton = 2131034137;
			
			// aapt resource value: 0x7f05001f
			public const int Settings = 2131034143;
			
			// aapt resource value: 0x7f05001b
			public const int SettingsButton = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int SocialButton = 2131034138;
			
			// aapt resource value: 0x7f050003
			public const int SubmitCompetitionButton = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int SubmitCustomGoalButton = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public const int SubmitCustomRewardButton = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int SubmitPredefinedGoalButton = 2131034122;
			
			// aapt resource value: 0x7f050026
			public const int UnlockedItemsButton = 2131034150;
			
			// aapt resource value: 0x7f050022
			public const int UnlockedItemsList = 2131034146;
			
			// aapt resource value: 0x7f050013
			public const int UpdateGoalButton = 2131034131;
			
			// aapt resource value: 0x7f050023
			public const int UpdateGoalForm = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int UpdateGoalSubmitButton = 2131034148;
			
			// aapt resource value: 0x7f05001d
			public const int ZadifyRewardsButton = 2131034141;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CompetitionsMenu = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CompletedGoalsMenu = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CreateCompetitionForm = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CreateCustomGoalForm = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int CreateGoalMenu = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int CreatePredefinedGoalForm = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int CreateRewardForm = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int CustomRewardDetailsScreen = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int CustomRewardsMenu = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int DeleteGoalForm = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int GoalDetailsScreen = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int GoalsMenu = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int MainMenu = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int NewsFeedScreen = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int RankDetailsScreen = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int RanksMenu = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int RewardsMenu = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int SettingsMenu = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int SocialMenu = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int UnlockedItemsScreen = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int UpdateGoalForm = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int ZadifyRewardsMenu = 2130903061;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
