#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Zadify.Resource", IsApplication=true)]

namespace Zadify
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050004
			public const int dietGoalTypes = 2131034116;
			
			// aapt resource value: 0x7f050009
			public const int dietWeights = 2131034121;
			
			// aapt resource value: 0x7f050003
			public const int financeGoalTypes = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int fitnessActivities = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int fitnessGoalTypes = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int fitnessWeights = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int predefinedGoalTypes = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int readingGoalTypes = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int readingItems = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int repeatingTimespans = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int writingGoalTypes = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public const int writingItems = 2131034123;
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int CompetitionForm = 2131099650;
			
			// aapt resource value: 0x7f0600ba
			public const int CompetitionsButton = 2131099834;
			
			// aapt resource value: 0x7f0600ab
			public const int CompletedGoalsButton = 2131099819;
			
			// aapt resource value: 0x7f060001
			public const int CompletedGoalsList = 2131099649;
			
			// aapt resource value: 0x7f0600a2
			public const int ConfirmDeleteGoalButton = 2131099810;
			
			// aapt resource value: 0x7f060014
			public const int CreateCompetitionButton = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int CreateCustomGoalButton = 2131099667;
			
			// aapt resource value: 0x7f0600a9
			public const int CreateGoalButton = 2131099817;
			
			// aapt resource value: 0x7f060012
			public const int CreatePredefinedGoalButton = 2131099666;
			
			// aapt resource value: 0x7f06009f
			public const int CreateRewardButton = 2131099807;
			
			// aapt resource value: 0x7f0600b4
			public const int CurrentRank = 2131099828;
			
			// aapt resource value: 0x7f06000c
			public const int CustomGoalDaysNumber = 2131099660;
			
			// aapt resource value: 0x7f060005
			public const int CustomGoalInnerLayout1 = 2131099653;
			
			// aapt resource value: 0x7f06000a
			public const int CustomGoalInnerLayout2 = 2131099658;
			
			// aapt resource value: 0x7f06000e
			public const int CustomGoalInnerLayout3 = 2131099662;
			
			// aapt resource value: 0x7f060008
			public const int CustomGoalItems = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int CustomGoalLayout = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int CustomGoalNumber = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int CustomGoalRepeatCheckbox = 2131099657;
			
			// aapt resource value: 0x7f060010
			public const int CustomGoalSelectDate = 2131099664;
			
			// aapt resource value: 0x7f060006
			public const int CustomGoalText1 = 2131099654;
			
			// aapt resource value: 0x7f06000b
			public const int CustomGoalText2 = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int CustomGoalText3 = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int CustomGoalText4 = 2131099663;
			
			// aapt resource value: 0x7f06009d
			public const int CustomRewardDetails = 2131099805;
			
			// aapt resource value: 0x7f06009b
			public const int CustomRewardForm = 2131099803;
			
			// aapt resource value: 0x7f0600b6
			public const int CustomRewardsButton = 2131099830;
			
			// aapt resource value: 0x7f0600a0
			public const int CustomRewardsList = 2131099808;
			
			// aapt resource value: 0x7f06009e
			public const int DeleteCustomRewardButton = 2131099806;
			
			// aapt resource value: 0x7f0600a8
			public const int DeleteGoalButton = 2131099816;
			
			// aapt resource value: 0x7f06008a
			public const int DietGainWeightInnerLayout1 = 2131099786;
			
			// aapt resource value: 0x7f06008e
			public const int DietGainWeightInnerLayout2 = 2131099790;
			
			// aapt resource value: 0x7f06008d
			public const int DietGainWeightItemsSpinner = 2131099789;
			
			// aapt resource value: 0x7f060089
			public const int DietGainWeightLayout = 2131099785;
			
			// aapt resource value: 0x7f06008c
			public const int DietGainWeightNumber = 2131099788;
			
			// aapt resource value: 0x7f060090
			public const int DietGainWeightSelectDate = 2131099792;
			
			// aapt resource value: 0x7f06008b
			public const int DietGainWeightText1 = 2131099787;
			
			// aapt resource value: 0x7f06008f
			public const int DietGainWeightText2 = 2131099791;
			
			// aapt resource value: 0x7f060087
			public const int DietGoalLayout = 2131099783;
			
			// aapt resource value: 0x7f060088
			public const int DietGoalTypeSpinner = 2131099784;
			
			// aapt resource value: 0x7f060093
			public const int DietLoseWeightInnerLayout1 = 2131099795;
			
			// aapt resource value: 0x7f060097
			public const int DietLoseWeightInnerLayout2 = 2131099799;
			
			// aapt resource value: 0x7f060096
			public const int DietLoseWeightItemsSpinner = 2131099798;
			
			// aapt resource value: 0x7f060092
			public const int DietLoseWeightLayout = 2131099794;
			
			// aapt resource value: 0x7f060095
			public const int DietLoseWeightNumber = 2131099797;
			
			// aapt resource value: 0x7f060099
			public const int DietLoseWeightSelectDate = 2131099801;
			
			// aapt resource value: 0x7f060094
			public const int DietLoseWeightText1 = 2131099796;
			
			// aapt resource value: 0x7f060098
			public const int DietLoseWeightText2 = 2131099800;
			
			// aapt resource value: 0x7f06002d
			public const int FinanceGoalLayout = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int FinanceGoalTypeSpinner = 2131099694;
			
			// aapt resource value: 0x7f060045
			public const int FinancePayByDateInnerLayout1 = 2131099717;
			
			// aapt resource value: 0x7f060049
			public const int FinancePayByDateInnerLayout2 = 2131099721;
			
			// aapt resource value: 0x7f060048
			public const int FinancePayByDateItemsSpinner = 2131099720;
			
			// aapt resource value: 0x7f060044
			public const int FinancePayByDateLayout = 2131099716;
			
			// aapt resource value: 0x7f060047
			public const int FinancePayByDateNumber = 2131099719;
			
			// aapt resource value: 0x7f06004b
			public const int FinancePayByDateSelectDate = 2131099723;
			
			// aapt resource value: 0x7f060046
			public const int FinancePayByDateText1 = 2131099718;
			
			// aapt resource value: 0x7f06004a
			public const int FinancePayByDateText2 = 2131099722;
			
			// aapt resource value: 0x7f06004e
			public const int FinancePayPerTimespanInnerLayout1 = 2131099726;
			
			// aapt resource value: 0x7f060052
			public const int FinancePayPerTimespanInnerLayout2 = 2131099730;
			
			// aapt resource value: 0x7f060055
			public const int FinancePayPerTimespanInnerLayout3 = 2131099733;
			
			// aapt resource value: 0x7f060051
			public const int FinancePayPerTimespanItemsSpinner = 2131099729;
			
			// aapt resource value: 0x7f06004d
			public const int FinancePayPerTimespanLayout = 2131099725;
			
			// aapt resource value: 0x7f060050
			public const int FinancePayPerTimespanNumber = 2131099728;
			
			// aapt resource value: 0x7f060057
			public const int FinancePayPerTimespanSelectDate = 2131099735;
			
			// aapt resource value: 0x7f06004f
			public const int FinancePayPerTimespanText1 = 2131099727;
			
			// aapt resource value: 0x7f060053
			public const int FinancePayPerTimespanText2 = 2131099731;
			
			// aapt resource value: 0x7f060056
			public const int FinancePayPerTimespanText3 = 2131099734;
			
			// aapt resource value: 0x7f060054
			public const int FinancePayPerTimespanTimespanSpinner = 2131099732;
			
			// aapt resource value: 0x7f060030
			public const int FinanceSaveByDateInnerLayout1 = 2131099696;
			
			// aapt resource value: 0x7f060034
			public const int FinanceSaveByDateInnerLayout2 = 2131099700;
			
			// aapt resource value: 0x7f060033
			public const int FinanceSaveByDateItemsSpinner = 2131099699;
			
			// aapt resource value: 0x7f06002f
			public const int FinanceSaveByDateLayout = 2131099695;
			
			// aapt resource value: 0x7f060032
			public const int FinanceSaveByDateNumber = 2131099698;
			
			// aapt resource value: 0x7f060036
			public const int FinanceSaveByDateSelectDate = 2131099702;
			
			// aapt resource value: 0x7f060031
			public const int FinanceSaveByDateText1 = 2131099697;
			
			// aapt resource value: 0x7f060035
			public const int FinanceSaveByDateText2 = 2131099701;
			
			// aapt resource value: 0x7f060039
			public const int FinanceSavePerTimespanInnerLayout1 = 2131099705;
			
			// aapt resource value: 0x7f06003d
			public const int FinanceSavePerTimespanInnerLayout2 = 2131099709;
			
			// aapt resource value: 0x7f060040
			public const int FinanceSavePerTimespanInnerLayout3 = 2131099712;
			
			// aapt resource value: 0x7f06003c
			public const int FinanceSavePerTimespanItemsSpinner = 2131099708;
			
			// aapt resource value: 0x7f060038
			public const int FinanceSavePerTimespanLayout = 2131099704;
			
			// aapt resource value: 0x7f06003b
			public const int FinanceSavePerTimespanNumber = 2131099707;
			
			// aapt resource value: 0x7f060042
			public const int FinanceSavePerTimespanSelectDate = 2131099714;
			
			// aapt resource value: 0x7f06003a
			public const int FinanceSavePerTimespanText1 = 2131099706;
			
			// aapt resource value: 0x7f06003e
			public const int FinanceSavePerTimespanText2 = 2131099710;
			
			// aapt resource value: 0x7f060041
			public const int FinanceSavePerTimespanText3 = 2131099713;
			
			// aapt resource value: 0x7f06003f
			public const int FinanceSavePerTimespanTimespanSpinner = 2131099711;
			
			// aapt resource value: 0x7f060019
			public const int FitnessByDateInnerLayout1 = 2131099673;
			
			// aapt resource value: 0x7f06001d
			public const int FitnessByDateInnerLayout2 = 2131099677;
			
			// aapt resource value: 0x7f06001c
			public const int FitnessByDateItemsSpinner = 2131099676;
			
			// aapt resource value: 0x7f060018
			public const int FitnessByDateLayout = 2131099672;
			
			// aapt resource value: 0x7f06001b
			public const int FitnessByDateNumber = 2131099675;
			
			// aapt resource value: 0x7f06001f
			public const int FitnessByDateSelectDate = 2131099679;
			
			// aapt resource value: 0x7f06001a
			public const int FitnessByDateText1 = 2131099674;
			
			// aapt resource value: 0x7f06001e
			public const int FitnessByDateText2 = 2131099678;
			
			// aapt resource value: 0x7f060016
			public const int FitnessGoalLayout = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int FitnessGoalTypeSpinner = 2131099671;
			
			// aapt resource value: 0x7f060022
			public const int FitnessPerTimespanInnerLayout1 = 2131099682;
			
			// aapt resource value: 0x7f060026
			public const int FitnessPerTimespanInnerLayout2 = 2131099686;
			
			// aapt resource value: 0x7f060029
			public const int FitnessPerTimespanInnerLayout3 = 2131099689;
			
			// aapt resource value: 0x7f060025
			public const int FitnessPerTimespanItemsSpinner = 2131099685;
			
			// aapt resource value: 0x7f060021
			public const int FitnessPerTimespanLayout = 2131099681;
			
			// aapt resource value: 0x7f060024
			public const int FitnessPerTimespanNumber = 2131099684;
			
			// aapt resource value: 0x7f06002b
			public const int FitnessPerTimespanSelectDate = 2131099691;
			
			// aapt resource value: 0x7f060023
			public const int FitnessPerTimespanText1 = 2131099683;
			
			// aapt resource value: 0x7f060027
			public const int FitnessPerTimespanText2 = 2131099687;
			
			// aapt resource value: 0x7f06002a
			public const int FitnessPerTimespanText3 = 2131099690;
			
			// aapt resource value: 0x7f060028
			public const int FitnessPerTimespanTimespanSpinner = 2131099688;
			
			// aapt resource value: 0x7f0600a3
			public const int GoalDetailsActionText = 2131099811;
			
			// aapt resource value: 0x7f0600a6
			public const int GoalDetailsAmountCompletedText = 2131099814;
			
			// aapt resource value: 0x7f0600a5
			public const int GoalDetailsDueDateText = 2131099813;
			
			// aapt resource value: 0x7f0600a4
			public const int GoalDetailsTimespanText = 2131099812;
			
			// aapt resource value: 0x7f0600a1
			public const int GoalDetailsTitle = 2131099809;
			
			// aapt resource value: 0x7f0600ac
			public const int GoalsButton = 2131099820;
			
			// aapt resource value: 0x7f0600aa
			public const int GoalsList = 2131099818;
			
			// aapt resource value: 0x7f0600b1
			public const int MonsterDemoButton = 2131099825;
			
			// aapt resource value: 0x7f0600b7
			public const int MonsterModeCheckbox = 2131099831;
			
			// aapt resource value: 0x7f0600b3
			public const int MonsterOKButton = 2131099827;
			
			// aapt resource value: 0x7f0600b2
			public const int MonsterText = 2131099826;
			
			// aapt resource value: 0x7f060000
			public const int NewCompetitionButton = 2131099648;
			
			// aapt resource value: 0x7f0600b9
			public const int NewsFeedButton = 2131099833;
			
			// aapt resource value: 0x7f060015
			public const int PredefinedGoalTypeSpinner = 2131099669;
			
			// aapt resource value: 0x7f0600c0
			public const int RanksButton = 2131099840;
			
			// aapt resource value: 0x7f06005c
			public const int ReadingByDateInnerLayout1 = 2131099740;
			
			// aapt resource value: 0x7f060060
			public const int ReadingByDateInnerLayout2 = 2131099744;
			
			// aapt resource value: 0x7f06005f
			public const int ReadingByDateItemsSpinner = 2131099743;
			
			// aapt resource value: 0x7f06005b
			public const int ReadingByDateLayout = 2131099739;
			
			// aapt resource value: 0x7f06005e
			public const int ReadingByDateNumber = 2131099742;
			
			// aapt resource value: 0x7f060062
			public const int ReadingByDateSelectDate = 2131099746;
			
			// aapt resource value: 0x7f06005d
			public const int ReadingByDateText1 = 2131099741;
			
			// aapt resource value: 0x7f060061
			public const int ReadingByDateText2 = 2131099745;
			
			// aapt resource value: 0x7f060059
			public const int ReadingGoalLayout = 2131099737;
			
			// aapt resource value: 0x7f06005a
			public const int ReadingGoalTypeSpinner = 2131099738;
			
			// aapt resource value: 0x7f060065
			public const int ReadingPerTimespanInnerLayout1 = 2131099749;
			
			// aapt resource value: 0x7f060069
			public const int ReadingPerTimespanInnerLayout2 = 2131099753;
			
			// aapt resource value: 0x7f06006c
			public const int ReadingPerTimespanInnerLayout3 = 2131099756;
			
			// aapt resource value: 0x7f060068
			public const int ReadingPerTimespanItemsSpinner = 2131099752;
			
			// aapt resource value: 0x7f060064
			public const int ReadingPerTimespanLayout = 2131099748;
			
			// aapt resource value: 0x7f060067
			public const int ReadingPerTimespanNumber = 2131099751;
			
			// aapt resource value: 0x7f06006e
			public const int ReadingPerTimespanSelectDate = 2131099758;
			
			// aapt resource value: 0x7f060066
			public const int ReadingPerTimespanText1 = 2131099750;
			
			// aapt resource value: 0x7f06006a
			public const int ReadingPerTimespanText2 = 2131099754;
			
			// aapt resource value: 0x7f06006d
			public const int ReadingPerTimespanText3 = 2131099757;
			
			// aapt resource value: 0x7f06006b
			public const int ReadingPerTimespanTimespanSpinner = 2131099755;
			
			// aapt resource value: 0x7f0600ad
			public const int RewardsButton = 2131099821;
			
			// aapt resource value: 0x7f0600b8
			public const int SaveSettingsButton = 2131099832;
			
			// aapt resource value: 0x7f0600af
			public const int SettingsButton = 2131099823;
			
			// aapt resource value: 0x7f0600b0
			public const int SetupButton = 2131099824;
			
			// aapt resource value: 0x7f0600ae
			public const int SocialButton = 2131099822;
			
			// aapt resource value: 0x7f060003
			public const int SubmitCompetitionButton = 2131099651;
			
			// aapt resource value: 0x7f060011
			public const int SubmitCustomGoalButton = 2131099665;
			
			// aapt resource value: 0x7f06009c
			public const int SubmitCustomRewardButton = 2131099804;
			
			// aapt resource value: 0x7f060091
			public const int SubmitDietGainWeightGoalButton = 2131099793;
			
			// aapt resource value: 0x7f06009a
			public const int SubmitDietLoseWeightGoalButton = 2131099802;
			
			// aapt resource value: 0x7f06004c
			public const int SubmitFinancePayByDateGoalButton = 2131099724;
			
			// aapt resource value: 0x7f060058
			public const int SubmitFinancePayPerTimespanGoalButton = 2131099736;
			
			// aapt resource value: 0x7f060037
			public const int SubmitFinanceSaveByDateGoalButton = 2131099703;
			
			// aapt resource value: 0x7f060043
			public const int SubmitFinanceSavePerTimespanGoalButton = 2131099715;
			
			// aapt resource value: 0x7f060020
			public const int SubmitFitnessByDateGoalButton = 2131099680;
			
			// aapt resource value: 0x7f06002c
			public const int SubmitFitnessPerTimespanGoalButton = 2131099692;
			
			// aapt resource value: 0x7f060063
			public const int SubmitReadingByDateGoalButton = 2131099747;
			
			// aapt resource value: 0x7f06006f
			public const int SubmitReadingPerTimespanGoalButton = 2131099759;
			
			// aapt resource value: 0x7f06007a
			public const int SubmitWritingByDateGoalButton = 2131099770;
			
			// aapt resource value: 0x7f060086
			public const int SubmitWritingPerTimespanGoalButton = 2131099782;
			
			// aapt resource value: 0x7f0600c1
			public const int UnlockedItemsButton = 2131099841;
			
			// aapt resource value: 0x7f0600bb
			public const int UnlockedItemsList = 2131099835;
			
			// aapt resource value: 0x7f0600a7
			public const int UpdateGoalButton = 2131099815;
			
			// aapt resource value: 0x7f0600bc
			public const int UpdateGoalLayout = 2131099836;
			
			// aapt resource value: 0x7f0600be
			public const int UpdateGoalNumber = 2131099838;
			
			// aapt resource value: 0x7f0600bf
			public const int UpdateGoalSubmitButton = 2131099839;
			
			// aapt resource value: 0x7f0600bd
			public const int UpdateGoalText = 2131099837;
			
			// aapt resource value: 0x7f060073
			public const int WritingByDateInnerLayout1 = 2131099763;
			
			// aapt resource value: 0x7f060077
			public const int WritingByDateInnerLayout2 = 2131099767;
			
			// aapt resource value: 0x7f060076
			public const int WritingByDateItemsSpinner = 2131099766;
			
			// aapt resource value: 0x7f060072
			public const int WritingByDateLayout = 2131099762;
			
			// aapt resource value: 0x7f060075
			public const int WritingByDateNumber = 2131099765;
			
			// aapt resource value: 0x7f060079
			public const int WritingByDateSelectDate = 2131099769;
			
			// aapt resource value: 0x7f060074
			public const int WritingByDateText1 = 2131099764;
			
			// aapt resource value: 0x7f060078
			public const int WritingByDateText2 = 2131099768;
			
			// aapt resource value: 0x7f060070
			public const int WritingGoalLayout = 2131099760;
			
			// aapt resource value: 0x7f060071
			public const int WritingGoalTypeSpinner = 2131099761;
			
			// aapt resource value: 0x7f06007c
			public const int WritingPerTimespanInnerLayout1 = 2131099772;
			
			// aapt resource value: 0x7f060080
			public const int WritingPerTimespanInnerLayout2 = 2131099776;
			
			// aapt resource value: 0x7f060083
			public const int WritingPerTimespanInnerLayout3 = 2131099779;
			
			// aapt resource value: 0x7f06007f
			public const int WritingPerTimespanItemsSpinner = 2131099775;
			
			// aapt resource value: 0x7f06007b
			public const int WritingPerTimespanLayout = 2131099771;
			
			// aapt resource value: 0x7f06007e
			public const int WritingPerTimespanNumber = 2131099774;
			
			// aapt resource value: 0x7f060085
			public const int WritingPerTimespanSelectDate = 2131099781;
			
			// aapt resource value: 0x7f06007d
			public const int WritingPerTimespanText1 = 2131099773;
			
			// aapt resource value: 0x7f060081
			public const int WritingPerTimespanText2 = 2131099777;
			
			// aapt resource value: 0x7f060084
			public const int WritingPerTimespanText3 = 2131099780;
			
			// aapt resource value: 0x7f060082
			public const int WritingPerTimespanTimespanSpinner = 2131099778;
			
			// aapt resource value: 0x7f0600b5
			public const int ZadifyRewardsButton = 2131099829;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CompetitionsMenu = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CompletedGoalsMenu = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CreateCompetitionForm = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CreateCustomGoalForm = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int CreateGoalMenu = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int CreatePredefinedGoalForm = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int CreateRewardForm = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int CustomRewardDetailsScreen = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int CustomRewardsMenu = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int DeleteGoalForm = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int GoalDetailsScreen = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int GoalsMenu = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int MainMenu = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int MonsterDisplay = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int NewsFeedScreen = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int RankDetailsScreen = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int RanksMenu = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int RewardsMenu = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int SettingsMenu = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int SocialMenu = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int UnlockedItemsScreen = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int UpdateGoalForm = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int ZadifyRewardsMenu = 2130903062;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int activityHint = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int applicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int numberHint = 2130968577;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
